management.security.enabled: false
security.basic.enabled: false

axon:
  amqp:
    exchange: accountEvents
  eventhandling:
    processors:
      amqpEvents:
        source: complaintEventsMethod

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop